repository:
  description: "A cute and functional calculator web application with a kawaii aesthetic, interactive face, and delightful animations. Try it live!"
  homepage: "https://daniel-hillman.github.io/kawaii-calculator/"
  topics:
    - calculator
    - kawaii
    - javascript
    - web-app
    - html5
    - css3
    - vanilla-javascript
    - cute
    - open-source